### ISSUE TITLE
REQ: OSX code uses deprecated audio feature that needs updating

### ISSUE THREAD

**Issue by javian** [ezQuake/ezquake-source#81]
When I run the latest (as of today) compiled code from git and spits out the following code in the osx terminal form which I ran it.

2016-03-14 21:32:50.085 ezquake-darwin-x86_64-dev[72788:9406395] 21:32:50.085 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by jite** [comment]
Are you building on your own here following the instructions in the repo or is it from Travis build?
What OSX version and what version of SDL2?

**Comment by javian** [comment]
I'm building on my own and using the instructions in the repo to compile. I only compile the executable and I'm not building the packaged app. Once compiled I move the output file to a fresh nQuake install. 
I installed the required libraries through homebrew.

`sdl2 ✔             sdl2_gfx ✔         sdl2_image ✔       sdl2_mixer ✔       sdl2_net ✔`

the main SDL2 package is version `sdl2: stable 2.0.4 (bottled)`and I'm on El Capitan 10.11.3.

**Comment by javian** [comment]
This seems to be a sdl problem and there's an upstream bug filed here

**Comment by javian** [comment]
This has been patched in SDL now so I'm assuming once 2.0.5 is released this issues should be resolved.

**Comment by fzwoch** [comment]
Once SDL with its patch is released your personal builds probably won't show this issue anymore. Since our Travis builds now build with support for 10.9 I would expect SDL builds will still continue to use the old API and therefore emit this notice.

**Comment by meag** [comment]
Closing - travis uses xcode 11.6, macOS 10.15.5
Fixed in https://hg.libsdl.org/SDL/rev/3115d38204aa
Travis target updated https://github.com/ezQuake/ezquake-source/commit/126296642a0dffd01193b56fca054d3de0586160#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485
